apiVersion: v1
kind: Pod
metadata:
  name: blank
  namespace: blank
spec:
  volumes:
    - name: volume
      emptyDir:
        sizeLimit: 500Mi
  terminationGracePeriodSeconds: 1
  containers:
    - name: main
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: volume
          mountPath: /volume
