apiVersion: v1
kind: Pod
metadata:
  generateName: test
  namespace: overlayfs-csi
spec:
  nodeName: node1
  terminationGracePeriodSeconds: 1
  volumes:
    - name: test
      csi:
        driver: overlayfs.csi.k8s.io
  containers:
    - name: test
      image: debian:bullseye-slim
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: test
          mountPath: /test
